version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_dev
    environment:
      - DOCKER_COMPOSE=True
    networks:
      - backend_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_dev
    environment:
      - DOCKER_COMPOSE=True
    depends_on:
      - backend
    networks:
      - backend_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - backend_network

networks:
  backend_network:
    name: backend_network
    driver: bridge